"""initial migration

Revision ID: cee2da195cb7
Revises: 
Create Date: 2024-10-23 22:05:20.685086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cee2da195cb7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('counties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('elections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('election_date', sa.String(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('constituencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('county_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['county_id'], ['counties.id'], name=op.f('fk_constituencies_county_id_counties')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('county_id', sa.Integer(), nullable=True),
    sa.Column('constituency_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['constituency_id'], ['constituencies.id'], name=op.f('fk_wards_constituency_id_constituencies')),
    sa.ForeignKeyConstraint(['county_id'], ['counties.id'], name=op.f('fk_wards_county_id_counties')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('voters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('national_id', sa.Integer(), nullable=True),
    sa.Column('registration_date', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('county_id', sa.Integer(), nullable=True),
    sa.Column('constituency_id', sa.Integer(), nullable=True),
    sa.Column('ward_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['constituency_id'], ['constituencies.id'], name=op.f('fk_voters_constituency_id_constituencies')),
    sa.ForeignKeyConstraint(['county_id'], ['counties.id'], name=op.f('fk_voters_county_id_counties')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_voters_user_id_users')),
    sa.ForeignKeyConstraint(['ward_id'], ['wards.id'], name=op.f('fk_voters_ward_id_wards')),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('national_id')
    )
    op.create_table('candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('voter_id', sa.Integer(), nullable=True),
    sa.Column('election_id', sa.Integer(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('party', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['election_id'], ['elections.id'], name=op.f('fk_candidates_election_id_elections')),
    sa.ForeignKeyConstraint(['voter_id'], ['voters.id'], name=op.f('fk_candidates_voter_id_voters')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=True),
    sa.Column('election_id', sa.Integer(), nullable=True),
    sa.Column('voter_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], name=op.f('fk_votes_candidate_id_candidates')),
    sa.ForeignKeyConstraint(['election_id'], ['elections.id'], name=op.f('fk_votes_election_id_elections')),
    sa.ForeignKeyConstraint(['voter_id'], ['voters.id'], name=op.f('fk_votes_voter_id_voters')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('votes')
    op.drop_table('candidates')
    op.drop_table('voters')
    op.drop_table('wards')
    op.drop_table('constituencies')
    op.drop_table('users')
    op.drop_table('elections')
    op.drop_table('counties')
    # ### end Alembic commands ###
